### ISSUE TITLE
nexusUsername & nexusPassword missing in gradle.properties file

### ISSUE THREAD

**Issue by debu-rnpr** [cesarferreira/RxPeople#3]

**Comment by cesarferreira** [comment]
Create a file in `~/.gradle/gradle.properties` with this:

```
nexusUsername='someusername'
nexusPassword='somepassword'
```

**Comment by debu-rnpr** [comment]
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'github.cesarferreira.rxpeople.models.FakeName github.cesarferreira.rxpeople.models.FakeUser.getName()' on a null object reference
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at github.cesarferreira.rxpeople.RxPeople$1.call(RxPeople.java:89)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at github.cesarferreira.rxpeople.RxPeople$1.call(RxPeople.java:83)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at retrofit.RxSupport$2.run(RxSupport.java:56)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-23 20:02:49.882 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at retrofit.Platform$Android$2$1.run(Platform.java:142)
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: github.cesarferreira.rxpeople.models.FetchedData.class
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
06-23 20:02:49.883 23705-23705/github.cesarferreira.rxpeople.sample W/System.err:   ... 7 more

In gradle.properties I have added
nexusUsername=someusername
nexusPassword=somepassword

**Comment by cesarferreira** [comment]
is the phone connected to the internet?
this has nothing to do with the nexusUsername

**Comment by debu-rnpr** [comment]
Ya the phone is connected to internet....tried multiple times , getting the same issue

**Comment by debu-rnpr** [comment]
Changing EncapsulatedUser to FakeUser solve the null pointer exception
